-- AUTOGENERATED BY ECS BUILD STEP
-- DO NOT EDIT
---@diagnostic disable: unused-local
---@diagnostic disable: missing-fields

-- START NAMESPACES

game_build = {}
logic = {}
ecs = {}
ecs.entity = {}
ecs.runtime = {}
ecs.runtime.components = {}
ecs.imgui = {}
ecs.imgui.components = {}

-- END NAMESPACES

-- START TYPES


-- END TYPES


---@diagnostic enable: unused-local
---@diagnostic enable: missing-fields

return {
	game_build = game_build,
	logic = logic,
	ecs = ecs,
}