-- AUTOGENERATED BY ECS BUILD STEP
-- DO NOT EDIT
---@diagnostic disable: unused-local
---@diagnostic disable: missing-fields

-- START NAMESPACES

local game_build = {}
local ecs = {}
ecs.imgui = {}
ecs.imgui.components = {}
ecs.game = {}
local logic = {}

-- END NAMESPACES

-- START TYPES

---@type ecs.game.GameActions
ecs.game.GameActions = {
  component_hash = -6795239468146607231,
  metatable_name = "ecs.game.GameActions_MetaTable",
}
---@type ecs.imgui.components.Button
ecs.imgui.components.Button = {
  component_hash = -5643622204316327033,
  metatable_name = "ecs.imgui.components.Button_MetaTable",
}
---@type game_build.TestComponent
game_build.TestComponent = {
  component_hash = -2616240389310087473,
  metatable_name = "game_build.TestComponent_MetaTable",
}
---@type logic.ButtonClose
logic.ButtonClose = {
  component_hash = 1528081635130897619,
  metatable_name = "logic.ButtonClose_MetaTable",
}
---@type logic.ButtonOpen
logic.ButtonOpen = {
  component_hash = -4984624697825475857,
  metatable_name = "logic.ButtonOpen_MetaTable",
}

-- END TYPES


---@diagnostic enable: unused-local
---@diagnostic enable: missing-fields

return {
	game_build = game_build,
	ecs = ecs,
	logic = logic,
}