-- AUTOGENERATED BY ECS BUILD STEP
-- DO NOT EDIT
---@meta
---@diagnostic disable: unused-local

-- START NAMESPACES

local game_build = {}
local ecs = {}
ecs.imgui = {}
ecs.imgui.components = {}
ecs.game = {}
local logic = {}

-- END NAMESPACES

-- START TYPES

---@class ecs.game.GameActions
---@field should_close boolean
---@field test_field integer?
---@field test_field_2 number?
---@field private component_hash integer
---@field private metatable_name string
ecs.game.GameActions = {}

---@class ecs.imgui.components.Button
---@field title string
---@field visible boolean
---@field clicked boolean
---@field private component_hash integer
---@field private metatable_name string
ecs.imgui.components.Button = {}

---@class game_build.TestComponent
---@field test_field boolean
---@field private component_hash integer
---@field private metatable_name string
game_build.TestComponent = {}

---@class logic.ButtonClose
---@field private component_hash integer
---@field private metatable_name string
logic.ButtonClose = {}

---@class logic.ButtonOpen
---@field private component_hash integer
---@field private metatable_name string
logic.ButtonOpen = {}


-- END TYPES


---@diagnostic enable: unused-local