-- AUTOGENERATED BY ECS BUILD STEP
-- DO NOT EDIT
---@meta
---@diagnostic disable: unused-local

-- START NAMESPACES

game_build = {}
ecs = {}
ecs.runtime = {}
ecs.runtime.components = {}
ecs.entity = {}
ecs.imgui = {}
ecs.imgui.components = {}
logic = {}

-- END NAMESPACES

-- START TYPES

---@class ecs.runtime.components.GameActions
---@field should_close boolean
---@field test_field integer?
---@field test_field_2 number?
---@field log Slice<string>
---@field private component_hash integer
---@field private metatable_name string
ecs.runtime.components.GameActions = {}

---@class ecs.entity.EntityId
---@field scene_id integer
---@field entity_id integer
---@field private component_hash integer
---@field private metatable_name string
ecs.entity.EntityId = {}

---@class ecs.imgui.components.Button
---@field title string
---@field visible boolean
---@field clicked boolean
---@field private component_hash integer
---@field private metatable_name string
ecs.imgui.components.Button = {}

---@class game_build.TestComponent
---@field test_field boolean
---@field private component_hash integer
---@field private metatable_name string
game_build.TestComponent = {}

---@class logic.ButtonClose
---@field private component_hash integer
---@field private metatable_name string
logic.ButtonClose = {}

---@class logic.ButtonOpen
---@field private component_hash integer
---@field private metatable_name string
logic.ButtonOpen = {}

---@class ecs.runtime.components.EventBuffer(usize)
---@field events Slice<integer>
---@field private component_hash integer
---@field private metatable_name string
ecs.runtime.components.EventBuffer(usize) = {}


-- END TYPES


---@diagnostic enable: unused-local